// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestMessage.proto

package com.scathon.tech.rpc.common.proto;

public final class RequestMsgEntity {
  private RequestMsgEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string serviceName = 2;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 2;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>string methodName = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    java.util.List<java.lang.String>
        getParamTypesList();
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    int getParamTypesCount();
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    java.lang.String getParamTypes(int index);
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    com.google.protobuf.ByteString
        getParamTypesBytes(int index);

    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getParamObjsList();
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    com.google.protobuf.Any getParamObjs(int index);
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    int getParamObjsCount();
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getParamObjsOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getParamObjsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RequestMessage}
   */
  public  static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMessage)
      RequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMessage() {
      requestId_ = "";
      serviceName_ = "";
      methodName_ = "";
      paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      paramObjs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                paramTypes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              paramTypes_.add(s);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                paramObjs_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000010;
              }
              paramObjs_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          paramTypes_ = paramTypes_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          paramObjs_ = java.util.Collections.unmodifiableList(paramObjs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.class, com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>string serviceName = 2;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string methodName = 3;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMTYPES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList paramTypes_;
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_;
    }
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    public java.lang.String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <code>repeated string paramTypes = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }

    public static final int PARAMOBJS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.Any> paramObjs_;
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    public java.util.List<com.google.protobuf.Any> getParamObjsList() {
      return paramObjs_;
    }
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getParamObjsOrBuilderList() {
      return paramObjs_;
    }
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    public int getParamObjsCount() {
      return paramObjs_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    public com.google.protobuf.Any getParamObjs(int index) {
      return paramObjs_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getParamObjsOrBuilder(
        int index) {
      return paramObjs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (!getServiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < paramTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, paramTypes_.getRaw(i));
      }
      for (int i = 0; i < paramObjs_.size(); i++) {
        output.writeMessage(5, paramObjs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (!getServiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamTypesList().size();
      }
      for (int i = 0; i < paramObjs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, paramObjs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage)) {
        return super.equals(obj);
      }
      com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage other = (com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamTypesList()
          .equals(other.getParamTypesList())) return false;
      if (!getParamObjsList()
          .equals(other.getParamObjsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamTypesCount() > 0) {
        hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypesList().hashCode();
      }
      if (getParamObjsCount() > 0) {
        hash = (37 * hash) + PARAMOBJS_FIELD_NUMBER;
        hash = (53 * hash) + getParamObjsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMessage)
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.class, com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.Builder.class);
      }

      // Construct using com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParamObjsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        serviceName_ = "";

        methodName_ = "";

        paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (paramObjsBuilder_ == null) {
          paramObjs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          paramObjsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage getDefaultInstanceForType() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage build() {
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage buildPartial() {
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage result = new com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.requestId_ = requestId_;
        result.serviceName_ = serviceName_;
        result.methodName_ = methodName_;
        if (((bitField0_ & 0x00000008) != 0)) {
          paramTypes_ = paramTypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.paramTypes_ = paramTypes_;
        if (paramObjsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            paramObjs_ = java.util.Collections.unmodifiableList(paramObjs_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.paramObjs_ = paramObjs_;
        } else {
          result.paramObjs_ = paramObjsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage) {
          return mergeFrom((com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage other) {
        if (other == com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.paramTypes_.isEmpty()) {
          if (paramTypes_.isEmpty()) {
            paramTypes_ = other.paramTypes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamTypesIsMutable();
            paramTypes_.addAll(other.paramTypes_);
          }
          onChanged();
        }
        if (paramObjsBuilder_ == null) {
          if (!other.paramObjs_.isEmpty()) {
            if (paramObjs_.isEmpty()) {
              paramObjs_ = other.paramObjs_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureParamObjsIsMutable();
              paramObjs_.addAll(other.paramObjs_);
            }
            onChanged();
          }
        } else {
          if (!other.paramObjs_.isEmpty()) {
            if (paramObjsBuilder_.isEmpty()) {
              paramObjsBuilder_.dispose();
              paramObjsBuilder_ = null;
              paramObjs_ = other.paramObjs_;
              bitField0_ = (bitField0_ & ~0x00000010);
              paramObjsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParamObjsFieldBuilder() : null;
            } else {
              paramObjsBuilder_.addAllMessages(other.paramObjs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 2;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public Builder clearServiceName() {
        
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 3;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamTypesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParamTypesList() {
        return paramTypes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public int getParamTypesCount() {
        return paramTypes_.size();
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public java.lang.String getParamTypes(int index) {
        return paramTypes_.get(index);
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public com.google.protobuf.ByteString
          getParamTypesBytes(int index) {
        return paramTypes_.getByteString(index);
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public Builder setParamTypes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypesIsMutable();
        paramTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public Builder addParamTypes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypesIsMutable();
        paramTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public Builder addAllParamTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public Builder clearParamTypes() {
        paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       */
      public Builder addParamTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> paramObjs_ =
        java.util.Collections.emptyList();
      private void ensureParamObjsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          paramObjs_ = new java.util.ArrayList<com.google.protobuf.Any>(paramObjs_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> paramObjsBuilder_;

      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any> getParamObjsList() {
        if (paramObjsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paramObjs_);
        } else {
          return paramObjsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public int getParamObjsCount() {
        if (paramObjsBuilder_ == null) {
          return paramObjs_.size();
        } else {
          return paramObjsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.Any getParamObjs(int index) {
        if (paramObjsBuilder_ == null) {
          return paramObjs_.get(index);
        } else {
          return paramObjsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder setParamObjs(
          int index, com.google.protobuf.Any value) {
        if (paramObjsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamObjsIsMutable();
          paramObjs_.set(index, value);
          onChanged();
        } else {
          paramObjsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder setParamObjs(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (paramObjsBuilder_ == null) {
          ensureParamObjsIsMutable();
          paramObjs_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramObjsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder addParamObjs(com.google.protobuf.Any value) {
        if (paramObjsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamObjsIsMutable();
          paramObjs_.add(value);
          onChanged();
        } else {
          paramObjsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder addParamObjs(
          int index, com.google.protobuf.Any value) {
        if (paramObjsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamObjsIsMutable();
          paramObjs_.add(index, value);
          onChanged();
        } else {
          paramObjsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder addParamObjs(
          com.google.protobuf.Any.Builder builderForValue) {
        if (paramObjsBuilder_ == null) {
          ensureParamObjsIsMutable();
          paramObjs_.add(builderForValue.build());
          onChanged();
        } else {
          paramObjsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder addParamObjs(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (paramObjsBuilder_ == null) {
          ensureParamObjsIsMutable();
          paramObjs_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramObjsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder addAllParamObjs(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (paramObjsBuilder_ == null) {
          ensureParamObjsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, paramObjs_);
          onChanged();
        } else {
          paramObjsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder clearParamObjs() {
        if (paramObjsBuilder_ == null) {
          paramObjs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          paramObjsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder removeParamObjs(int index) {
        if (paramObjsBuilder_ == null) {
          ensureParamObjsIsMutable();
          paramObjs_.remove(index);
          onChanged();
        } else {
          paramObjsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.Any.Builder getParamObjsBuilder(
          int index) {
        return getParamObjsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getParamObjsOrBuilder(
          int index) {
        if (paramObjsBuilder_ == null) {
          return paramObjs_.get(index);  } else {
          return paramObjsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getParamObjsOrBuilderList() {
        if (paramObjsBuilder_ != null) {
          return paramObjsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paramObjs_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.Any.Builder addParamObjsBuilder() {
        return getParamObjsFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.Any.Builder addParamObjsBuilder(
          int index) {
        return getParamObjsFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any paramObjs = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getParamObjsBuilderList() {
        return getParamObjsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getParamObjsFieldBuilder() {
        if (paramObjsBuilder_ == null) {
          paramObjsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  paramObjs_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          paramObjs_ = null;
        }
        return paramObjsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
    private static final com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage();
    }

    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
      @java.lang.Override
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RequestMessage.proto\032\031google/protobuf/" +
      "any.proto\"\211\001\n\016RequestMessage\022\021\n\trequestI" +
      "d\030\001 \001(\t\022\023\n\013serviceName\030\002 \001(\t\022\022\n\nmethodNa" +
      "me\030\003 \001(\t\022\022\n\nparamTypes\030\004 \003(\t\022\'\n\tparamObj" +
      "s\030\005 \003(\0132\024.google.protobuf.AnyB5\n!com.sca" +
      "thon.tech.rpc.common.protoB\020RequestMsgEn" +
      "tityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMessage_descriptor,
        new java.lang.String[] { "RequestId", "ServiceName", "MethodName", "ParamTypes", "ParamObjs", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
