// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestMessage.proto

package com.scathon.tech.rpc.common.proto;

public final class RequestMsgEntity {
  private RequestMsgEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestUUID = 1;</code>
     */
    java.lang.String getRequestUUID();
    /**
     * <code>string requestUUID = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestUUIDBytes();

    /**
     * <code>string serviceName = 2;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 2;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>string methodName = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>.google.protobuf.Any paramTypes = 4;</code>
     */
    boolean hasParamTypes();
    /**
     * <code>.google.protobuf.Any paramTypes = 4;</code>
     */
    com.google.protobuf.Any getParamTypes();
    /**
     * <code>.google.protobuf.Any paramTypes = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getParamTypesOrBuilder();

    /**
     * <code>.google.protobuf.Any paramObjs = 5;</code>
     */
    boolean hasParamObjs();
    /**
     * <code>.google.protobuf.Any paramObjs = 5;</code>
     */
    com.google.protobuf.Any getParamObjs();
    /**
     * <code>.google.protobuf.Any paramObjs = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getParamObjsOrBuilder();
  }
  /**
   * Protobuf type {@code RequestMessage}
   */
  public  static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMessage)
      RequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMessage() {
      requestUUID_ = "";
      serviceName_ = "";
      methodName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestUUID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (paramTypes_ != null) {
                subBuilder = paramTypes_.toBuilder();
              }
              paramTypes_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(paramTypes_);
                paramTypes_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (paramObjs_ != null) {
                subBuilder = paramObjs_.toBuilder();
              }
              paramObjs_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(paramObjs_);
                paramObjs_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.class, com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.Builder.class);
    }

    public static final int REQUESTUUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestUUID_;
    /**
     * <code>string requestUUID = 1;</code>
     */
    public java.lang.String getRequestUUID() {
      java.lang.Object ref = requestUUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestUUID_ = s;
        return s;
      }
    }
    /**
     * <code>string requestUUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestUUIDBytes() {
      java.lang.Object ref = requestUUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>string serviceName = 2;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string methodName = 3;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMTYPES_FIELD_NUMBER = 4;
    private com.google.protobuf.Any paramTypes_;
    /**
     * <code>.google.protobuf.Any paramTypes = 4;</code>
     */
    public boolean hasParamTypes() {
      return paramTypes_ != null;
    }
    /**
     * <code>.google.protobuf.Any paramTypes = 4;</code>
     */
    public com.google.protobuf.Any getParamTypes() {
      return paramTypes_ == null ? com.google.protobuf.Any.getDefaultInstance() : paramTypes_;
    }
    /**
     * <code>.google.protobuf.Any paramTypes = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getParamTypesOrBuilder() {
      return getParamTypes();
    }

    public static final int PARAMOBJS_FIELD_NUMBER = 5;
    private com.google.protobuf.Any paramObjs_;
    /**
     * <code>.google.protobuf.Any paramObjs = 5;</code>
     */
    public boolean hasParamObjs() {
      return paramObjs_ != null;
    }
    /**
     * <code>.google.protobuf.Any paramObjs = 5;</code>
     */
    public com.google.protobuf.Any getParamObjs() {
      return paramObjs_ == null ? com.google.protobuf.Any.getDefaultInstance() : paramObjs_;
    }
    /**
     * <code>.google.protobuf.Any paramObjs = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getParamObjsOrBuilder() {
      return getParamObjs();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestUUID_);
      }
      if (!getServiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      if (paramTypes_ != null) {
        output.writeMessage(4, getParamTypes());
      }
      if (paramObjs_ != null) {
        output.writeMessage(5, getParamObjs());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestUUID_);
      }
      if (!getServiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      if (paramTypes_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getParamTypes());
      }
      if (paramObjs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getParamObjs());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage)) {
        return super.equals(obj);
      }
      com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage other = (com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage) obj;

      if (!getRequestUUID()
          .equals(other.getRequestUUID())) return false;
      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (hasParamTypes() != other.hasParamTypes()) return false;
      if (hasParamTypes()) {
        if (!getParamTypes()
            .equals(other.getParamTypes())) return false;
      }
      if (hasParamObjs() != other.hasParamObjs()) return false;
      if (hasParamObjs()) {
        if (!getParamObjs()
            .equals(other.getParamObjs())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTUUID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestUUID().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (hasParamTypes()) {
        hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypes().hashCode();
      }
      if (hasParamObjs()) {
        hash = (37 * hash) + PARAMOBJS_FIELD_NUMBER;
        hash = (53 * hash) + getParamObjs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMessage)
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.class, com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.Builder.class);
      }

      // Construct using com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestUUID_ = "";

        serviceName_ = "";

        methodName_ = "";

        if (paramTypesBuilder_ == null) {
          paramTypes_ = null;
        } else {
          paramTypes_ = null;
          paramTypesBuilder_ = null;
        }
        if (paramObjsBuilder_ == null) {
          paramObjs_ = null;
        } else {
          paramObjs_ = null;
          paramObjsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage getDefaultInstanceForType() {
        return com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage build() {
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage buildPartial() {
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage result = new com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage(this);
        result.requestUUID_ = requestUUID_;
        result.serviceName_ = serviceName_;
        result.methodName_ = methodName_;
        if (paramTypesBuilder_ == null) {
          result.paramTypes_ = paramTypes_;
        } else {
          result.paramTypes_ = paramTypesBuilder_.build();
        }
        if (paramObjsBuilder_ == null) {
          result.paramObjs_ = paramObjs_;
        } else {
          result.paramObjs_ = paramObjsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage) {
          return mergeFrom((com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage other) {
        if (other == com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage.getDefaultInstance()) return this;
        if (!other.getRequestUUID().isEmpty()) {
          requestUUID_ = other.requestUUID_;
          onChanged();
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasParamTypes()) {
          mergeParamTypes(other.getParamTypes());
        }
        if (other.hasParamObjs()) {
          mergeParamObjs(other.getParamObjs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestUUID_ = "";
      /**
       * <code>string requestUUID = 1;</code>
       */
      public java.lang.String getRequestUUID() {
        java.lang.Object ref = requestUUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestUUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestUUID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestUUIDBytes() {
        java.lang.Object ref = requestUUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestUUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestUUID = 1;</code>
       */
      public Builder setRequestUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestUUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestUUID = 1;</code>
       */
      public Builder clearRequestUUID() {
        
        requestUUID_ = getDefaultInstance().getRequestUUID();
        onChanged();
        return this;
      }
      /**
       * <code>string requestUUID = 1;</code>
       */
      public Builder setRequestUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestUUID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 2;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public Builder clearServiceName() {
        
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 3;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any paramTypes_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> paramTypesBuilder_;
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public boolean hasParamTypes() {
        return paramTypesBuilder_ != null || paramTypes_ != null;
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public com.google.protobuf.Any getParamTypes() {
        if (paramTypesBuilder_ == null) {
          return paramTypes_ == null ? com.google.protobuf.Any.getDefaultInstance() : paramTypes_;
        } else {
          return paramTypesBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public Builder setParamTypes(com.google.protobuf.Any value) {
        if (paramTypesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          paramTypes_ = value;
          onChanged();
        } else {
          paramTypesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public Builder setParamTypes(
          com.google.protobuf.Any.Builder builderForValue) {
        if (paramTypesBuilder_ == null) {
          paramTypes_ = builderForValue.build();
          onChanged();
        } else {
          paramTypesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public Builder mergeParamTypes(com.google.protobuf.Any value) {
        if (paramTypesBuilder_ == null) {
          if (paramTypes_ != null) {
            paramTypes_ =
              com.google.protobuf.Any.newBuilder(paramTypes_).mergeFrom(value).buildPartial();
          } else {
            paramTypes_ = value;
          }
          onChanged();
        } else {
          paramTypesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public Builder clearParamTypes() {
        if (paramTypesBuilder_ == null) {
          paramTypes_ = null;
          onChanged();
        } else {
          paramTypes_ = null;
          paramTypesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public com.google.protobuf.Any.Builder getParamTypesBuilder() {
        
        onChanged();
        return getParamTypesFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getParamTypesOrBuilder() {
        if (paramTypesBuilder_ != null) {
          return paramTypesBuilder_.getMessageOrBuilder();
        } else {
          return paramTypes_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : paramTypes_;
        }
      }
      /**
       * <code>.google.protobuf.Any paramTypes = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getParamTypesFieldBuilder() {
        if (paramTypesBuilder_ == null) {
          paramTypesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getParamTypes(),
                  getParentForChildren(),
                  isClean());
          paramTypes_ = null;
        }
        return paramTypesBuilder_;
      }

      private com.google.protobuf.Any paramObjs_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> paramObjsBuilder_;
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public boolean hasParamObjs() {
        return paramObjsBuilder_ != null || paramObjs_ != null;
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.Any getParamObjs() {
        if (paramObjsBuilder_ == null) {
          return paramObjs_ == null ? com.google.protobuf.Any.getDefaultInstance() : paramObjs_;
        } else {
          return paramObjsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder setParamObjs(com.google.protobuf.Any value) {
        if (paramObjsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          paramObjs_ = value;
          onChanged();
        } else {
          paramObjsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder setParamObjs(
          com.google.protobuf.Any.Builder builderForValue) {
        if (paramObjsBuilder_ == null) {
          paramObjs_ = builderForValue.build();
          onChanged();
        } else {
          paramObjsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder mergeParamObjs(com.google.protobuf.Any value) {
        if (paramObjsBuilder_ == null) {
          if (paramObjs_ != null) {
            paramObjs_ =
              com.google.protobuf.Any.newBuilder(paramObjs_).mergeFrom(value).buildPartial();
          } else {
            paramObjs_ = value;
          }
          onChanged();
        } else {
          paramObjsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public Builder clearParamObjs() {
        if (paramObjsBuilder_ == null) {
          paramObjs_ = null;
          onChanged();
        } else {
          paramObjs_ = null;
          paramObjsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.Any.Builder getParamObjsBuilder() {
        
        onChanged();
        return getParamObjsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getParamObjsOrBuilder() {
        if (paramObjsBuilder_ != null) {
          return paramObjsBuilder_.getMessageOrBuilder();
        } else {
          return paramObjs_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : paramObjs_;
        }
      }
      /**
       * <code>.google.protobuf.Any paramObjs = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getParamObjsFieldBuilder() {
        if (paramObjsBuilder_ == null) {
          paramObjsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getParamObjs(),
                  getParentForChildren(),
                  isClean());
          paramObjs_ = null;
        }
        return paramObjsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
    private static final com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage();
    }

    public static com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
      @java.lang.Override
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.scathon.tech.rpc.common.proto.RequestMsgEntity.RequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RequestMessage.proto\032\031google/protobuf/" +
      "any.proto\"\241\001\n\016RequestMessage\022\023\n\013requestU" +
      "UID\030\001 \001(\t\022\023\n\013serviceName\030\002 \001(\t\022\022\n\nmethod" +
      "Name\030\003 \001(\t\022(\n\nparamTypes\030\004 \001(\0132\024.google." +
      "protobuf.Any\022\'\n\tparamObjs\030\005 \001(\0132\024.google" +
      ".protobuf.AnyB5\n!com.scathon.tech.rpc.co" +
      "mmon.protoB\020RequestMsgEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMessage_descriptor,
        new java.lang.String[] { "RequestUUID", "ServiceName", "MethodName", "ParamTypes", "ParamObjs", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
