// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseMessage.proto

package com.scathon.tech.rpc.common.proto;

public final class ResponseMsgEntity {
  private ResponseMsgEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string status = 2;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 2;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string errMsg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>string errMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getResponseBodyList();
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    com.google.protobuf.Any getResponseBody(int index);
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    int getResponseBodyCount();
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getResponseBodyOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getResponseBodyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResponseMessage}
   */
  public  static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseMessage)
      ResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessage() {
      requestId_ = "";
      status_ = "";
      errMsg_ = "";
      responseBody_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errMsg_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                responseBody_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000008;
              }
              responseBody_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          responseBody_ = java.util.Collections.unmodifiableList(responseBody_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scathon.tech.rpc.common.proto.ResponseMsgEntity.internal_static_ResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scathon.tech.rpc.common.proto.ResponseMsgEntity.internal_static_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.class, com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 2;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errMsg_;
    /**
     * <code>string errMsg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string errMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSEBODY_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.Any> responseBody_;
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    public java.util.List<com.google.protobuf.Any> getResponseBodyList() {
      return responseBody_;
    }
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getResponseBodyOrBuilderList() {
      return responseBody_;
    }
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    public int getResponseBodyCount() {
      return responseBody_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    public com.google.protobuf.Any getResponseBody(int index) {
      return responseBody_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any responseBody = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getResponseBodyOrBuilder(
        int index) {
      return responseBody_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
      }
      for (int i = 0; i < responseBody_.size(); i++) {
        output.writeMessage(4, responseBody_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
      }
      for (int i = 0; i < responseBody_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, responseBody_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage)) {
        return super.equals(obj);
      }
      com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage other = (com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getErrMsg()
          .equals(other.getErrMsg())) return false;
      if (!getResponseBodyList()
          .equals(other.getResponseBodyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrMsg().hashCode();
      if (getResponseBodyCount() > 0) {
        hash = (37 * hash) + RESPONSEBODY_FIELD_NUMBER;
        hash = (53 * hash) + getResponseBodyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseMessage)
        com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scathon.tech.rpc.common.proto.ResponseMsgEntity.internal_static_ResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scathon.tech.rpc.common.proto.ResponseMsgEntity.internal_static_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.class, com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.Builder.class);
      }

      // Construct using com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResponseBodyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        status_ = "";

        errMsg_ = "";

        if (responseBodyBuilder_ == null) {
          responseBody_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          responseBodyBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scathon.tech.rpc.common.proto.ResponseMsgEntity.internal_static_ResponseMessage_descriptor;
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage getDefaultInstanceForType() {
        return com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage build() {
        com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage buildPartial() {
        com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage result = new com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.requestId_ = requestId_;
        result.status_ = status_;
        result.errMsg_ = errMsg_;
        if (responseBodyBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            responseBody_ = java.util.Collections.unmodifiableList(responseBody_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.responseBody_ = responseBody_;
        } else {
          result.responseBody_ = responseBodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage) {
          return mergeFrom((com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage other) {
        if (other == com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (responseBodyBuilder_ == null) {
          if (!other.responseBody_.isEmpty()) {
            if (responseBody_.isEmpty()) {
              responseBody_ = other.responseBody_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureResponseBodyIsMutable();
              responseBody_.addAll(other.responseBody_);
            }
            onChanged();
          }
        } else {
          if (!other.responseBody_.isEmpty()) {
            if (responseBodyBuilder_.isEmpty()) {
              responseBodyBuilder_.dispose();
              responseBodyBuilder_ = null;
              responseBody_ = other.responseBody_;
              bitField0_ = (bitField0_ & ~0x00000008);
              responseBodyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResponseBodyFieldBuilder() : null;
            } else {
              responseBodyBuilder_.addAllMessages(other.responseBody_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 2;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>string errMsg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errMsg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errMsg = 3;</code>
       */
      public Builder clearErrMsg() {
        
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string errMsg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errMsg_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> responseBody_ =
        java.util.Collections.emptyList();
      private void ensureResponseBodyIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          responseBody_ = new java.util.ArrayList<com.google.protobuf.Any>(responseBody_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> responseBodyBuilder_;

      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public java.util.List<com.google.protobuf.Any> getResponseBodyList() {
        if (responseBodyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(responseBody_);
        } else {
          return responseBodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public int getResponseBodyCount() {
        if (responseBodyBuilder_ == null) {
          return responseBody_.size();
        } else {
          return responseBodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public com.google.protobuf.Any getResponseBody(int index) {
        if (responseBodyBuilder_ == null) {
          return responseBody_.get(index);
        } else {
          return responseBodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder setResponseBody(
          int index, com.google.protobuf.Any value) {
        if (responseBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResponseBodyIsMutable();
          responseBody_.set(index, value);
          onChanged();
        } else {
          responseBodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder setResponseBody(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (responseBodyBuilder_ == null) {
          ensureResponseBodyIsMutable();
          responseBody_.set(index, builderForValue.build());
          onChanged();
        } else {
          responseBodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder addResponseBody(com.google.protobuf.Any value) {
        if (responseBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResponseBodyIsMutable();
          responseBody_.add(value);
          onChanged();
        } else {
          responseBodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder addResponseBody(
          int index, com.google.protobuf.Any value) {
        if (responseBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResponseBodyIsMutable();
          responseBody_.add(index, value);
          onChanged();
        } else {
          responseBodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder addResponseBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (responseBodyBuilder_ == null) {
          ensureResponseBodyIsMutable();
          responseBody_.add(builderForValue.build());
          onChanged();
        } else {
          responseBodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder addResponseBody(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (responseBodyBuilder_ == null) {
          ensureResponseBodyIsMutable();
          responseBody_.add(index, builderForValue.build());
          onChanged();
        } else {
          responseBodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder addAllResponseBody(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (responseBodyBuilder_ == null) {
          ensureResponseBodyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, responseBody_);
          onChanged();
        } else {
          responseBodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder clearResponseBody() {
        if (responseBodyBuilder_ == null) {
          responseBody_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          responseBodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public Builder removeResponseBody(int index) {
        if (responseBodyBuilder_ == null) {
          ensureResponseBodyIsMutable();
          responseBody_.remove(index);
          onChanged();
        } else {
          responseBodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public com.google.protobuf.Any.Builder getResponseBodyBuilder(
          int index) {
        return getResponseBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getResponseBodyOrBuilder(
          int index) {
        if (responseBodyBuilder_ == null) {
          return responseBody_.get(index);  } else {
          return responseBodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getResponseBodyOrBuilderList() {
        if (responseBodyBuilder_ != null) {
          return responseBodyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(responseBody_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public com.google.protobuf.Any.Builder addResponseBodyBuilder() {
        return getResponseBodyFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public com.google.protobuf.Any.Builder addResponseBodyBuilder(
          int index) {
        return getResponseBodyFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any responseBody = 4;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getResponseBodyBuilderList() {
        return getResponseBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getResponseBodyFieldBuilder() {
        if (responseBodyBuilder_ == null) {
          responseBodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  responseBody_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          responseBody_ = null;
        }
        return responseBodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:ResponseMessage)
    private static final com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage();
    }

    public static com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
      @java.lang.Override
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.scathon.tech.rpc.common.proto.ResponseMsgEntity.ResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ResponseMessage.proto\032\031google/protobuf" +
      "/any.proto\"p\n\017ResponseMessage\022\021\n\trequest" +
      "Id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\016\n\006errMsg\030\003 \001(\t" +
      "\022*\n\014responseBody\030\004 \003(\0132\024.google.protobuf" +
      ".AnyB6\n!com.scathon.tech.rpc.common.prot" +
      "oB\021ResponseMsgEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMessage_descriptor,
        new java.lang.String[] { "RequestId", "Status", "ErrMsg", "ResponseBody", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
